/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type { RouteRecordInfo } from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analyze': RouteRecordInfo<'/analyze', '/analyze', Record<never, never>, Record<never, never>>,
    '/config/sensors': RouteRecordInfo<'/config/sensors', '/config/sensors', Record<never, never>, Record<never, never>>,
    '/config/storage': RouteRecordInfo<'/config/storage', '/config/storage', Record<never, never>, Record<never, never>>,
    '/config/tools': RouteRecordInfo<'/config/tools', '/config/tools', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/measure': RouteRecordInfo<'/measure', '/measure', Record<never, never>, Record<never, never>>,
  }
}
