// This file is auto-generated by @hey-api/openapi-ts

export const $ADCValues = {
    properties: {
        prescaler: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prescaler'
        },
        acquisition_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acquisition Time'
        },
        oversampling_rate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oversampling Rate'
        },
        reference_voltage: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Voltage'
        }
    },
    type: 'object',
    required: ['prescaler', 'acquisition_time', 'oversampling_rate', 'reference_voltage'],
    title: 'ADCValues'
} as const;

export const $APIStateModel = {
    properties: {
        can_ready: {
            type: 'boolean',
            title: 'Can Ready'
        },
        disk_capacity: {
            '$ref': '#/components/schemas/DiskCapacity'
        },
        measurement_status: {
            '$ref': '#/components/schemas/MeasurementStatus'
        }
    },
    type: 'object',
    required: ['can_ready', 'disk_capacity', 'measurement_status'],
    title: 'APIStateModel'
} as const;

export const $Body_post_analyzed_file_api_v1_files_analyze_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_post_analyzed_file_api_v1_files_analyze_post'
} as const;

export const $Body_sth_connect_api_v1_sth_connect_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        }
    },
    type: 'object',
    required: ['mac'],
    title: 'Body_sth_connect_api_v1_sth_connect_put'
} as const;

export const $Body_stu_connected_api_v1_stu_connected_post = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_connected_api_v1_stu_connected_post'
} as const;

export const $Body_stu_disable_ota_api_v1_stu_ota_disable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_disable_ota_api_v1_stu_ota_disable_put'
} as const;

export const $Body_stu_enable_ota_api_v1_stu_ota_enable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_enable_ota_api_v1_stu_ota_enable_put'
} as const;

export const $Body_stu_reset_api_v1_stu_reset_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_reset_api_v1_stu_reset_put'
} as const;

export const $Body_write_adc_api_v1_sth_write_adc_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        },
        config: {
            '$ref': '#/components/schemas/ADCValues'
        }
    },
    type: 'object',
    required: ['mac', 'config'],
    title: 'Body_write_adc_api_v1_sth_write_adc_put'
} as const;

export const $CANResponseError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'CANResponseError'
} as const;

export const $ConnectionTimeoutError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'ConnectionTimeoutError'
} as const;

export const $ControlResponse = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            '$ref': '#/components/schemas/MeasurementStatus'
        }
    },
    type: 'object',
    required: ['message', 'data'],
    title: 'ControlResponse'
} as const;

export const $DiskCapacity = {
    properties: {
        total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        available: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available'
        }
    },
    type: 'object',
    required: ['total', 'available'],
    title: 'DiskCapacity'
} as const;

export const $FileListResponseModel = {
    properties: {
        capacity: {
            '$ref': '#/components/schemas/DiskCapacity'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileDetails'
            },
            type: 'array',
            title: 'Files'
        },
        directory: {
            type: 'string',
            title: 'Directory'
        }
    },
    type: 'object',
    required: ['capacity', 'files', 'directory'],
    title: 'FileListResponseModel'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $MeasurementFileDetails = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        created: {
            type: 'string',
            title: 'Created'
        },
        size: {
            type: 'integer',
            title: 'Size'
        }
    },
    type: 'object',
    required: ['name', 'created', 'size'],
    title: 'MeasurementFileDetails'
} as const;

export const $MeasurementInstructions = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        mac: {
            type: 'string',
            title: 'Mac'
        },
        time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time'
        },
        first: {
            type: 'integer',
            title: 'First'
        },
        second: {
            type: 'integer',
            title: 'Second'
        },
        third: {
            type: 'integer',
            title: 'Third'
        },
        ift_requested: {
            type: 'boolean',
            title: 'Ift Requested'
        },
        ift_channel: {
            type: 'string',
            title: 'Ift Channel'
        },
        ift_window_width: {
            type: 'integer',
            title: 'Ift Window Width'
        }
    },
    type: 'object',
    required: ['name', 'mac', 'time', 'first', 'second', 'third', 'ift_requested', 'ift_channel', 'ift_window_width'],
    title: 'MeasurementInstructions'
} as const;

export const $MeasurementStatus = {
    properties: {
        running: {
            type: 'boolean',
            title: 'Running'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        tool_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tool Name'
        },
        tool_mac: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tool Mac'
        }
    },
    type: 'object',
    required: ['running'],
    title: 'MeasurementStatus'
} as const;

export const $STHDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        rssi: {
            type: 'integer',
            title: 'Rssi'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address', 'rssi'],
    title: 'STHDeviceResponseModel',
    description: 'Wrapper for STH Device class implementing Pydantic features'
} as const;

export const $STHRenameRequestModel = {
    properties: {
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        }
    },
    type: 'object',
    required: ['mac_address', 'new_name'],
    title: 'STHRenameRequestModel'
} as const;

export const $STHRenameResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        old_name: {
            type: 'string',
            title: 'Old Name'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'old_name', 'mac_address'],
    title: 'STHRenameResponseModel',
    description: 'Response Model for renaming a STH device'
} as const;

export const $STUDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address'],
    title: 'STUDeviceResponseModel'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;