// This file is auto-generated by @hey-api/openapi-ts

export const $ADCValues = {
    properties: {
        prescaler: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prescaler'
        },
        acquisition_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acquisition Time'
        },
        oversampling_rate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oversampling Rate'
        },
        reference_voltage: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Voltage'
        }
    },
    type: 'object',
    required: ['prescaler', 'acquisition_time', 'oversampling_rate', 'reference_voltage'],
    title: 'ADCValues'
} as const;

export const $Body_post_analyzed_file_api_v1_files_analyze_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_post_analyzed_file_api_v1_files_analyze_post'
} as const;

export const $Body_sth_connect_api_v1_sth_connect_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        }
    },
    type: 'object',
    required: ['mac'],
    title: 'Body_sth_connect_api_v1_sth_connect_put'
} as const;

export const $Body_stu_connected_api_v1_stu_connected_post = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_connected_api_v1_stu_connected_post'
} as const;

export const $Body_stu_disable_ota_api_v1_stu_ota_disable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_disable_ota_api_v1_stu_ota_disable_put'
} as const;

export const $Body_stu_enable_ota_api_v1_stu_ota_enable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_enable_ota_api_v1_stu_ota_enable_put'
} as const;

export const $Body_stu_reset_api_v1_stu_reset_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_reset_api_v1_stu_reset_put'
} as const;

export const $Body_upload_file_api_v1_cloud_upload_post = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename'
        }
    },
    type: 'object',
    required: ['filename'],
    title: 'Body_upload_file_api_v1_cloud_upload_post'
} as const;

export const $Body_write_adc_api_v1_sth_write_adc_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        },
        config: {
            '$ref': '#/components/schemas/ADCValues'
        }
    },
    type: 'object',
    required: ['mac', 'config'],
    title: 'Body_write_adc_api_v1_sth_write_adc_put'
} as const;

export const $CANResponseError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'CANResponseError'
} as const;

export const $ConnectionTimeoutError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'ConnectionTimeoutError'
} as const;

export const $ControlResponse = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            '$ref': '#/components/schemas/MeasurementStatus'
        }
    },
    type: 'object',
    required: ['message', 'data'],
    title: 'ControlResponse'
} as const;

export const $CoolantEnum = {
    type: 'string',
    enum: ['Dry', 'Air', 'MMQ', 'Flood', 'Oil'],
    title: 'CoolantEnum'
} as const;

export const $DiskCapacity = {
    properties: {
        total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        available: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available'
        }
    },
    type: 'object',
    required: ['total', 'available'],
    title: 'DiskCapacity'
} as const;

export const $FileCloudDetails = {
    properties: {
        is_uploaded: {
            type: 'boolean',
            title: 'Is Uploaded'
        },
        upload_timestamp: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upload Timestamp'
        }
    },
    type: 'object',
    required: ['is_uploaded', 'upload_timestamp'],
    title: 'FileCloudDetails'
} as const;

export const $FileListResponseModel = {
    properties: {
        capacity: {
            '$ref': '#/components/schemas/DiskCapacity'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileDetails'
            },
            type: 'array',
            title: 'Files'
        },
        directory: {
            type: 'string',
            title: 'Directory'
        }
    },
    type: 'object',
    required: ['capacity', 'files', 'directory'],
    title: 'FileListResponseModel'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $InstitutionEnum = {
    type: 'string',
    enum: ['TU Wien', 'TU Darmstadt'],
    title: 'InstitutionEnum'
} as const;

export const $LogFileMeta = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        first_timestamp: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Timestamp'
        },
        last_timestamp: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Timestamp'
        }
    },
    type: 'object',
    required: ['name', 'size', 'first_timestamp', 'last_timestamp'],
    title: 'LogFileMeta'
} as const;

export const $LogListResponse = {
    properties: {
        files: {
            items: {
                '$ref': '#/components/schemas/LogFileMeta'
            },
            type: 'array',
            title: 'Files'
        },
        directory: {
            type: 'string',
            title: 'Directory'
        },
        max_bytes: {
            type: 'integer',
            title: 'Max Bytes'
        },
        backup_count: {
            type: 'integer',
            title: 'Backup Count'
        }
    },
    type: 'object',
    required: ['files', 'directory', 'max_bytes', 'backup_count'],
    title: 'LogListResponse'
} as const;

export const $LogResponse = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['filename', 'content'],
    title: 'LogResponse'
} as const;

export const $MeasurementFileDetails = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        created: {
            type: 'string',
            title: 'Created'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        cloud: {
            '$ref': '#/components/schemas/FileCloudDetails'
        }
    },
    type: 'object',
    required: ['name', 'created', 'size', 'cloud'],
    title: 'MeasurementFileDetails'
} as const;

export const $MeasurementInstructionChannel = {
    properties: {
        channel_number: {
            type: 'integer',
            title: 'Channel Number'
        },
        sensor_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor Id'
        }
    },
    type: 'object',
    required: ['channel_number', 'sensor_id'],
    title: 'MeasurementInstructionChannel'
} as const;

export const $MeasurementInstructions_Input = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        mac: {
            type: 'string',
            title: 'Mac'
        },
        time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time'
        },
        first: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        second: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        third: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        ift_requested: {
            type: 'boolean',
            title: 'Ift Requested'
        },
        ift_channel: {
            type: 'string',
            title: 'Ift Channel'
        },
        ift_window_width: {
            type: 'integer',
            title: 'Ift Window Width'
        },
        adc: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ADCValues'
                },
                {
                    type: 'null'
                }
            ]
        },
        meta: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Metadata'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name', 'mac', 'time', 'first', 'second', 'third', 'ift_requested', 'ift_channel', 'ift_window_width', 'adc', 'meta'],
    title: 'MeasurementInstructions'
} as const;

export const $MeasurementInstructions_Output = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        mac: {
            type: 'string',
            title: 'Mac'
        },
        time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time'
        },
        first: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        second: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        third: {
            '$ref': '#/components/schemas/MeasurementInstructionChannel'
        },
        ift_requested: {
            type: 'boolean',
            title: 'Ift Requested'
        },
        ift_channel: {
            type: 'string',
            title: 'Ift Channel'
        },
        ift_window_width: {
            type: 'integer',
            title: 'Ift Window Width'
        },
        adc: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ADCValues'
                },
                {
                    type: 'null'
                }
            ]
        },
        meta: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Metadata'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name', 'mac', 'time', 'first', 'second', 'third', 'ift_requested', 'ift_channel', 'ift_window_width', 'adc', 'meta'],
    title: 'MeasurementInstructions'
} as const;

export const $MeasurementSocketMessage = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Metadata'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['message', 'data'],
    title: 'MeasurementSocketMessage'
} as const;

export const $MeasurementStatus = {
    properties: {
        running: {
            type: 'boolean',
            title: 'Running'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        tool_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tool Name'
        },
        instructions: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MeasurementInstructions-Output'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['running'],
    title: 'MeasurementStatus'
} as const;

export const $Metadata = {
    properties: {
        version: {
            type: 'string',
            title: 'Version'
        },
        profile: {
            type: 'string',
            title: 'Profile'
        },
        parameters: {
            additionalProperties: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/Quantity'
                    },
                    {}
                ]
            },
            type: 'object',
            title: 'Parameters'
        }
    },
    type: 'object',
    required: ['version', 'profile', 'parameters'],
    title: 'Metadata'
} as const;

export const $ProcessEnum = {
    type: 'string',
    enum: ['milling', 'drilling', 'grinding', 'turning', 'reaming', 'shaping', 'thread_cutting', 'thread_milling', 'thread_forming'],
    title: 'ProcessEnum'
} as const;

export const $Quantity = {
    properties: {
        value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Value'
        },
        unit: {
            type: 'string',
            title: 'Unit'
        }
    },
    type: 'object',
    required: ['value', 'unit'],
    title: 'Quantity'
} as const;

export const $STHDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        rssi: {
            type: 'integer',
            title: 'Rssi'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address', 'rssi'],
    title: 'STHDeviceResponseModel',
    description: 'Wrapper for STH Device class implementing Pydantic features'
} as const;

export const $STHRenameRequestModel = {
    properties: {
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        }
    },
    type: 'object',
    required: ['mac_address', 'new_name'],
    title: 'STHRenameRequestModel'
} as const;

export const $STHRenameResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        old_name: {
            type: 'string',
            title: 'Old Name'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'old_name', 'mac_address'],
    title: 'STHRenameResponseModel',
    description: 'Response Model for renaming a STH device'
} as const;

export const $STUDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address'],
    title: 'STUDeviceResponseModel'
} as const;

export const $Sensor = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        sensor_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor Type'
        },
        sensor_id: {
            type: 'string',
            title: 'Sensor Id'
        },
        unit: {
            type: 'string',
            title: 'Unit'
        },
        phys_min: {
            type: 'number',
            title: 'Phys Min'
        },
        phys_max: {
            type: 'number',
            title: 'Phys Max'
        },
        volt_min: {
            type: 'number',
            title: 'Volt Min'
        },
        volt_max: {
            type: 'number',
            title: 'Volt Max'
        },
        scaling_factor: {
            type: 'number',
            title: 'Scaling Factor',
            default: 1
        },
        offset: {
            type: 'number',
            title: 'Offset',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'sensor_type', 'sensor_id', 'unit', 'phys_min', 'phys_max', 'volt_min', 'volt_max'],
    title: 'Sensor'
} as const;

export const $SystemStateModel = {
    properties: {
        can_ready: {
            type: 'boolean',
            title: 'Can Ready'
        },
        disk_capacity: {
            '$ref': '#/components/schemas/DiskCapacity'
        },
        measurement_status: {
            '$ref': '#/components/schemas/MeasurementStatus'
        },
        cloud_status: {
            type: 'boolean',
            title: 'Cloud Status'
        }
    },
    type: 'object',
    required: ['can_ready', 'disk_capacity', 'measurement_status', 'cloud_status'],
    title: 'SystemStateModel',
    description: 'Data model for API state'
} as const;

export const $ToolMaterialEnum = {
    type: 'string',
    enum: ['Carbide (P40)', 'Carbide', 'MCD', 'Ceramic', 'PCD'],
    title: 'ToolMaterialEnum'
} as const;

export const $TridentBucketObject = {
    properties: {
        Key: {
            type: 'string',
            title: 'Key'
        },
        LastModified: {
            type: 'string',
            title: 'Lastmodified'
        },
        ETag: {
            type: 'string',
            title: 'Etag'
        },
        Size: {
            type: 'integer',
            title: 'Size'
        },
        StorageClass: {
            type: 'string',
            title: 'Storageclass'
        }
    },
    type: 'object',
    required: ['Key', 'LastModified', 'ETag', 'Size', 'StorageClass'],
    title: 'TridentBucketObject'
} as const;

export const $UnifiedMetadata = {
    properties: {
        person: {
            type: 'string',
            title: 'Person'
        },
        institution: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InstitutionEnum'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Institution'
        },
        machine: {
            type: 'string',
            title: 'Machine'
        },
        experiment: {
            type: 'string',
            title: 'Experiment'
        },
        process: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProcessEnum'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Process'
        },
        workpiece_material: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WorkpieceMaterialEnum'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Workpiece Material'
        },
        cutting_speed: {
            type: 'number',
            title: 'Cutting Speed'
        },
        feed_per_tooth: {
            type: 'number',
            title: 'Feed Per Tooth'
        },
        doc_axial: {
            type: 'number',
            title: 'Doc Axial'
        },
        doc_radial: {
            type: 'number',
            title: 'Doc Radial'
        },
        tool_diameter: {
            type: 'number',
            title: 'Tool Diameter'
        },
        tool_tooth_count: {
            type: 'integer',
            title: 'Tool Tooth Count'
        },
        tool_material: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ToolMaterialEnum'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Tool Material'
        },
        tool_offset: {
            type: 'number',
            title: 'Tool Offset'
        },
        coolant: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CoolantEnum'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Coolant'
        },
        sth_mac: {
            type: 'string',
            title: 'Sth Mac'
        },
        stu_mac: {
            type: 'string',
            title: 'Stu Mac'
        },
        tool_failure: {
            type: 'boolean',
            title: 'Tool Failure'
        },
        wear_mark_width: {
            type: 'number',
            title: 'Wear Mark Width'
        },
        twm_layer: {
            type: 'integer',
            title: 'Twm Layer'
        },
        feed_per_rev: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feed Per Rev'
        },
        doc: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc'
        },
        workpiece_diameter: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workpiece Diameter'
        },
        pictures: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pictures'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['person', 'institution', 'machine', 'experiment', 'process', 'workpiece_material', 'cutting_speed', 'feed_per_tooth', 'doc_axial', 'doc_radial', 'tool_diameter', 'tool_tooth_count', 'tool_material', 'tool_offset', 'coolant', 'sth_mac', 'stu_mac', 'tool_failure', 'wear_mark_width', 'twm_layer'],
    title: 'UnifiedMetadata'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $WorkpieceMaterialEnum = {
    type: 'string',
    enum: ['C45', 'Steel'],
    title: 'WorkpieceMaterialEnum'
} as const;