// This file is auto-generated by @hey-api/openapi-ts

export const $ADCValues = {
    properties: {
        prescaler: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prescaler'
        },
        acquisition_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acquisition Time'
        },
        oversampling_rate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oversampling Rate'
        },
        reference_voltage: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Voltage'
        }
    },
    type: 'object',
    required: ['prescaler', 'acquisition_time', 'oversampling_rate', 'reference_voltage'],
    title: 'ADCValues'
} as const;

export const $APIStateModel = {
    properties: {
        can_ready: {
            type: 'boolean',
            title: 'Can Ready'
        }
    },
    type: 'object',
    required: ['can_ready'],
    title: 'APIStateModel'
} as const;

export const $Body_post_analyzed_file_api_v1_files_analyze_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_post_analyzed_file_api_v1_files_analyze_post'
} as const;

export const $Body_sth_connect_api_v1_sth_connect_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        }
    },
    type: 'object',
    required: ['mac'],
    title: 'Body_sth_connect_api_v1_sth_connect_put'
} as const;

export const $Body_stu_disable_ota_api_v1_stu_ota_disable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_disable_ota_api_v1_stu_ota_disable_put'
} as const;

export const $Body_stu_enable_ota_api_v1_stu_ota_enable_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_enable_ota_api_v1_stu_ota_enable_put'
} as const;

export const $Body_stu_reset_api_v1_stu_reset_put = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Body_stu_reset_api_v1_stu_reset_put'
} as const;

export const $Body_write_adc_api_v1_sth_write_adc_put = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        },
        config: {
            '$ref': '#/components/schemas/ADCValues'
        }
    },
    type: 'object',
    required: ['mac', 'config'],
    title: 'Body_write_adc_api_v1_sth_write_adc_put'
} as const;

export const $ConnectionTimeoutError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'ConnectionTimeoutError'
} as const;

export const $Dataset = {
    properties: {
        data: {
            items: {
                type: 'number'
            },
            type: 'array',
            title: 'Data'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['data', 'name'],
    title: 'Dataset'
} as const;

export const $DiskCapacity = {
    properties: {
        total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        available: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available'
        }
    },
    type: 'object',
    required: ['total', 'available'],
    title: 'DiskCapacity'
} as const;

export const $FileListResponseModel = {
    properties: {
        capacity: {
            '$ref': '#/components/schemas/DiskCapacity'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileDetails'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['capacity', 'files'],
    title: 'FileListResponseModel'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $MeasurementFileDetails = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        created: {
            type: 'string',
            title: 'Created'
        },
        size: {
            type: 'integer',
            title: 'Size'
        }
    },
    type: 'object',
    required: ['name', 'created', 'size'],
    title: 'MeasurementFileDetails'
} as const;

export const $NoResponseError = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['name', 'message'],
    title: 'NoResponseError'
} as const;

export const $ParsedMeasurement = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        counter: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Counter'
        },
        timestamp: {
            items: {
                type: 'number'
            },
            type: 'array',
            title: 'Timestamp'
        },
        datasets: {
            items: {
                '$ref': '#/components/schemas/Dataset'
            },
            type: 'array',
            title: 'Datasets'
        }
    },
    type: 'object',
    required: ['name', 'counter', 'timestamp', 'datasets'],
    title: 'ParsedMeasurement'
} as const;

export const $STHDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        rssi: {
            type: 'integer',
            title: 'Rssi'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address', 'rssi'],
    title: 'STHDeviceResponseModel',
    description: 'Wrapper for STH Device class implementing Pydantic features'
} as const;

export const $STHRenameRequestModel = {
    properties: {
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        }
    },
    type: 'object',
    required: ['mac_address', 'new_name'],
    title: 'STHRenameRequestModel'
} as const;

export const $STHRenameResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        old_name: {
            type: 'string',
            title: 'Old Name'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'old_name', 'mac_address'],
    title: 'STHRenameResponseModel',
    description: 'Response Model for renaming a STH device'
} as const;

export const $STUDeviceResponseModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_number: {
            type: 'integer',
            title: 'Device Number'
        },
        mac_address: {
            type: 'string',
            title: 'Mac Address'
        }
    },
    type: 'object',
    required: ['name', 'device_number', 'mac_address'],
    title: 'STUDeviceResponseModel'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;