// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { StuApiV1StuGetResponse, StuResetApiV1StuResetPutData, StuResetApiV1StuResetPutResponse, StuEnableOtaApiV1StuOtaEnablePutData, StuEnableOtaApiV1StuOtaEnablePutResponse, StuDisableOtaApiV1StuOtaDisablePutData, StuDisableOtaApiV1StuOtaDisablePutResponse, StuConnectedApiV1StuConnectedPostData, StuConnectedApiV1StuConnectedPostResponse, SthApiV1SthGetResponse, SthConnectApiV1SthConnectPutData, SthConnectApiV1SthConnectPutResponse, SthDisconnectApiV1SthDisconnectPutResponse, SthRenameApiV1SthRenamePutData, SthRenameApiV1SthRenamePutResponse, ReadAdcApiV1SthReadAdcMacGetData, ReadAdcApiV1SthReadAdcMacGetResponse, WriteAdcApiV1SthWriteAdcPutData, WriteAdcApiV1SthWriteAdcPutResponse, PingApiV1PingGetResponse, ResetCanApiV1ResetCanPutResponse, ListFilesAndCapacityApiV1FilesGetResponse, DownloadFileApiV1FilesNameGetData, DownloadFileApiV1FilesNameGetResponse, DeleteFileApiV1FilesNameDeleteData, DeleteFileApiV1FilesNameDeleteResponse, GetAnalyzedFileApiV1FilesAnalyzeNameGetData, GetAnalyzedFileApiV1FilesAnalyzeNameGetResponse, PostAnalyzedFileApiV1FilesAnalyzePostData, PostAnalyzedFileApiV1FilesAnalyzePostResponse, StartMeasurementApiV1MeasurementStartPostData, StartMeasurementApiV1MeasurementStartPostResponse, StopMeasurementApiV1MeasurementStopPostResponse, MeasurementStatusApiV1MeasurementGetResponse } from './types.gen';

/**
 * Stu
 * @returns unknown Return the STU Devices connected to the system
 * @returns void Indicates no STU Devices connected to the system
 * @throws ApiError
 */
export const stuApiV1StuGet = (): CancelablePromise<StuApiV1StuGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/stu',
    errors: {
        404: 'Not found'
    }
}); };

/**
 * Stu Reset
 * @param data The data for the request.
 * @param data.requestBody
 * @returns void Device was successfully reset.
 * @throws ApiError
 */
export const stuResetApiV1StuResetPut = (data: StuResetApiV1StuResetPutData): CancelablePromise<StuResetApiV1StuResetPutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/stu/reset',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error',
        502: 'The CAN Network did not respond. This can either be because the Node is not connected, or the Network is unresponsive.'
    }
}); };

/**
 * Stu Enable Ota
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const stuEnableOtaApiV1StuOtaEnablePut = (data: StuEnableOtaApiV1StuOtaEnablePutData): CancelablePromise<StuEnableOtaApiV1StuOtaEnablePutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/stu/ota/enable',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error'
    }
}); };

/**
 * Stu Disable Ota
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const stuDisableOtaApiV1StuOtaDisablePut = (data: StuDisableOtaApiV1StuOtaDisablePutData): CancelablePromise<StuDisableOtaApiV1StuOtaDisablePutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/stu/ota/disable',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error'
    }
}); };

/**
 * Stu Connected
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const stuConnectedApiV1StuConnectedPost = (data: StuConnectedApiV1StuConnectedPostData): CancelablePromise<StuConnectedApiV1StuConnectedPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/stu/connected',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error'
    }
}); };

/**
 * Sth
 * @returns unknown Return the STH Devices reachable
 * @throws ApiError
 */
export const sthApiV1SthGet = (): CancelablePromise<SthApiV1SthGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/sth',
    errors: {
        404: 'Not found'
    }
}); };

/**
 * Sth Connect
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Connection was successful
 * @throws ApiError
 */
export const sthConnectApiV1SthConnectPut = (data: SthConnectApiV1SthConnectPutData): CancelablePromise<SthConnectApiV1SthConnectPutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/sth/connect',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Indicates no STH Devices in reach',
        422: 'Validation Error'
    }
}); };

/**
 * Sth Disconnect
 * @returns unknown Disconnection was successful
 * @throws ApiError
 */
export const sthDisconnectApiV1SthDisconnectPut = (): CancelablePromise<SthDisconnectApiV1SthDisconnectPutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/sth/disconnect',
    errors: {
        404: 'Indicates error in disconnection'
    }
}); };

/**
 * Sth Rename
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Rename was successful
 * @throws ApiError
 */
export const sthRenameApiV1SthRenamePut = (data: SthRenameApiV1SthRenamePutData): CancelablePromise<SthRenameApiV1SthRenamePutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/sth/rename',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error',
        502: 'Indicates error in rename'
    }
}); };

/**
 * Read Adc
 * @param data The data for the request.
 * @param data.mac
 * @returns unknown ADC reading was successful
 * @throws ApiError
 */
export const readAdcApiV1SthReadAdcMacGet = (data: ReadAdcApiV1SthReadAdcMacGetData): CancelablePromise<ReadAdcApiV1SthReadAdcMacGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/sth/read-adc/{mac}',
    path: {
        mac: data.mac
    },
    errors: {
        404: 'Not found',
        422: 'Validation Error',
        504: 'ADC reading timed out'
    }
}); };

/**
 * Write Adc
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown ADC writing was successful
 * @throws ApiError
 */
export const writeAdcApiV1SthWriteAdcPut = (data: WriteAdcApiV1SthWriteAdcPutData): CancelablePromise<WriteAdcApiV1SthWriteAdcPutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/sth/write-adc',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        404: 'Not found',
        422: 'Validation Error',
        504: 'ADC writing timed out'
    }
}); };

/**
 * Ping
 * @returns APIStateModel Successful Response
 * @throws ApiError
 */
export const pingApiV1PingGet = (): CancelablePromise<PingApiV1PingGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/ping'
}); };

/**
 * Reset Can
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const resetCanApiV1ResetCanPut = (): CancelablePromise<ResetCanApiV1ResetCanPutResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/v1/reset-can'
}); };

/**
 * List Files And Capacity
 * @returns FileListResponseModel Successful Response
 * @throws ApiError
 */
export const listFilesAndCapacityApiV1FilesGet = (): CancelablePromise<ListFilesAndCapacityApiV1FilesGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/files'
}); };

/**
 * Download File
 * @param data The data for the request.
 * @param data.name
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const downloadFileApiV1FilesNameGet = (data: DownloadFileApiV1FilesNameGetData): CancelablePromise<DownloadFileApiV1FilesNameGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/files/{name}',
    path: {
        name: data.name
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete File
 * @param data The data for the request.
 * @param data.name
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const deleteFileApiV1FilesNameDelete = (data: DeleteFileApiV1FilesNameDeleteData): CancelablePromise<DeleteFileApiV1FilesNameDeleteResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/v1/files/{name}',
    path: {
        name: data.name
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Get Analyzed File
 * @param data The data for the request.
 * @param data.name
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const getAnalyzedFileApiV1FilesAnalyzeNameGet = (data: GetAnalyzedFileApiV1FilesAnalyzeNameGetData): CancelablePromise<GetAnalyzedFileApiV1FilesAnalyzeNameGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/files/analyze/{name}',
    path: {
        name: data.name
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Post Analyzed File
 * @param data The data for the request.
 * @param data.formData
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const postAnalyzedFileApiV1FilesAnalyzePost = (data: PostAnalyzedFileApiV1FilesAnalyzePostData): CancelablePromise<PostAnalyzedFileApiV1FilesAnalyzePostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/files/analyze',
    formData: data.formData,
    mediaType: 'multipart/form-data',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Start Measurement
 * @param data The data for the request.
 * @param data.requestBody
 * @returns ControlResponse Successful Response
 * @throws ApiError
 */
export const startMeasurementApiV1MeasurementStartPost = (data: StartMeasurementApiV1MeasurementStartPostData): CancelablePromise<StartMeasurementApiV1MeasurementStartPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/measurement/start',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Stop Measurement
 * @returns ControlResponse Successful Response
 * @throws ApiError
 */
export const stopMeasurementApiV1MeasurementStopPost = (): CancelablePromise<StopMeasurementApiV1MeasurementStopPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/measurement/stop'
}); };

/**
 * Measurement Status
 * @returns MeasurementStatus Successful Response
 * @throws ApiError
 */
export const measurementStatusApiV1MeasurementGet = (): CancelablePromise<MeasurementStatusApiV1MeasurementGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/measurement'
}); };