// This file is auto-generated by @hey-api/openapi-ts

export type ADCValues = {
    prescaler: number | null;
    acquisition_time: number | null;
    oversampling_rate: number | null;
    reference_voltage: number | null;
};

export type APIStateModel = {
    can_ready: boolean;
    disk_capacity: DiskCapacity;
};

export type Body_post_analyzed_file_api_v1_files_analyze_post = {
    file: (Blob | File);
};

export type Body_sth_connect_api_v1_sth_connect_put = {
    mac: string;
};

export type Body_stu_connected_api_v1_stu_connected_post = {
    name: string;
};

export type Body_stu_disable_ota_api_v1_stu_ota_disable_put = {
    name: string;
};

export type Body_stu_enable_ota_api_v1_stu_ota_enable_put = {
    name: string;
};

export type Body_stu_reset_api_v1_stu_reset_put = {
    name: string;
};

export type Body_write_adc_api_v1_sth_write_adc_put = {
    mac: string;
    config: ADCValues;
};

export type CANResponseError = {
    name: string;
    message: string;
};

export type ConnectionTimeoutError = {
    name: string;
    message: string;
};

export type DiskCapacity = {
    total: number | null;
    available: number | null;
};

export type FileListResponseModel = {
    capacity: DiskCapacity;
    files: Array<MeasurementFileDetails>;
    directory: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MeasurementFileDetails = {
    name: string;
    created: string;
    size: number;
};

/**
 * Wrapper for STH Device class implementing Pydantic features
 */
export type STHDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
    rssi: number;
};

export type STHRenameRequestModel = {
    mac_address: string;
    new_name: string;
};

/**
 * Response Model for renaming a STH device
 */
export type STHRenameResponseModel = {
    name: string;
    old_name: string;
    mac_address: string;
};

export type STUDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type StuApiV1StuGetResponse = unknown | void;

export type StuResetApiV1StuResetPutData = {
    requestBody: Body_stu_reset_api_v1_stu_reset_put;
};

export type StuResetApiV1StuResetPutResponse = void;

export type StuEnableOtaApiV1StuOtaEnablePutData = {
    requestBody: Body_stu_enable_ota_api_v1_stu_ota_enable_put;
};

export type StuEnableOtaApiV1StuOtaEnablePutResponse = CANResponseError | null;

export type StuDisableOtaApiV1StuOtaDisablePutData = {
    requestBody: Body_stu_disable_ota_api_v1_stu_ota_disable_put;
};

export type StuDisableOtaApiV1StuOtaDisablePutResponse = CANResponseError | null;

export type StuConnectedApiV1StuConnectedPostData = {
    requestBody: Body_stu_connected_api_v1_stu_connected_post;
};

export type StuConnectedApiV1StuConnectedPostResponse = unknown;

export type SthApiV1SthGetResponse = unknown;

export type SthConnectApiV1SthConnectPutData = {
    requestBody: Body_sth_connect_api_v1_sth_connect_put;
};

export type SthConnectApiV1SthConnectPutResponse = unknown;

export type SthDisconnectApiV1SthDisconnectPutResponse = unknown;

export type SthRenameApiV1SthRenamePutData = {
    requestBody: STHRenameRequestModel;
};

export type SthRenameApiV1SthRenamePutResponse = unknown;

export type ReadAdcApiV1SthReadAdcMacGetData = {
    mac: string;
};

export type ReadAdcApiV1SthReadAdcMacGetResponse = unknown;

export type WriteAdcApiV1SthWriteAdcPutData = {
    requestBody: Body_write_adc_api_v1_sth_write_adc_put;
};

export type WriteAdcApiV1SthWriteAdcPutResponse = unknown;

export type PingApiV1PingGetResponse = APIStateModel;

export type ResetCanApiV1ResetCanPutResponse = unknown;

export type ListFilesAndCapacityApiV1FilesGetResponse = FileListResponseModel;

export type DownloadFileApiV1FilesNameGetData = {
    name: string;
};

export type DownloadFileApiV1FilesNameGetResponse = unknown;

export type DeleteFileApiV1FilesNameDeleteData = {
    name: string;
};

export type DeleteFileApiV1FilesNameDeleteResponse = unknown;

export type GetAnalyzedFileApiV1FilesAnalyzeNameGetData = {
    name: string;
};

export type GetAnalyzedFileApiV1FilesAnalyzeNameGetResponse = unknown;

export type PostAnalyzedFileApiV1FilesAnalyzePostData = {
    formData: Body_post_analyzed_file_api_v1_files_analyze_post;
};

export type PostAnalyzedFileApiV1FilesAnalyzePostResponse = unknown;

export type $OpenApiTs = {
    '/api/v1/stu': {
        get: {
            res: {
                /**
                 * Return the STU Devices connected to the system
                 */
                200: unknown;
                /**
                 * Indicates no STU Devices connected to the system
                 */
                204: void;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/stu/reset': {
        put: {
            req: StuResetApiV1StuResetPutData;
            res: {
                /**
                 * Device was successfully reset.
                 */
                204: void;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * The CAN Network did not respond. This can either be because the Node is not connected, or the Network is unresponsive.
                 */
                502: unknown;
            };
        };
    };
    '/api/v1/stu/ota/enable': {
        put: {
            req: StuEnableOtaApiV1StuOtaEnablePutData;
            res: {
                /**
                 * Successful Response
                 */
                200: CANResponseError | null;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/stu/ota/disable': {
        put: {
            req: StuDisableOtaApiV1StuOtaDisablePutData;
            res: {
                /**
                 * Successful Response
                 */
                200: CANResponseError | null;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/stu/connected': {
        post: {
            req: StuConnectedApiV1StuConnectedPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/sth': {
        get: {
            res: {
                /**
                 * Return the STH Devices reachable
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/sth/connect': {
        put: {
            req: SthConnectApiV1SthConnectPutData;
            res: {
                /**
                 * Connection was successful
                 */
                200: unknown;
                /**
                 * Indicates no STH Devices in reach
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/sth/disconnect': {
        put: {
            res: {
                /**
                 * Disconnection was successful
                 */
                200: unknown;
                /**
                 * Indicates error in disconnection
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/sth/rename': {
        put: {
            req: SthRenameApiV1SthRenamePutData;
            res: {
                /**
                 * Rename was successful
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * Indicates error in rename
                 */
                502: unknown;
            };
        };
    };
    '/api/v1/sth/read-adc/{mac}': {
        get: {
            req: ReadAdcApiV1SthReadAdcMacGetData;
            res: {
                /**
                 * ADC reading was successful
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * ADC reading timed out
                 */
                504: unknown;
            };
        };
    };
    '/api/v1/sth/write-adc': {
        put: {
            req: WriteAdcApiV1SthWriteAdcPutData;
            res: {
                /**
                 * ADC writing was successful
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * ADC writing timed out
                 */
                504: unknown;
            };
        };
    };
    '/api/v1/ping': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: APIStateModel;
            };
        };
    };
    '/api/v1/reset-can': {
        put: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/files': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: FileListResponseModel;
            };
        };
    };
    '/api/v1/files/{name}': {
        get: {
            req: DownloadFileApiV1FilesNameGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteFileApiV1FilesNameDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/files/analyze/{name}': {
        get: {
            req: GetAnalyzedFileApiV1FilesAnalyzeNameGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/files/analyze': {
        post: {
            req: PostAnalyzedFileApiV1FilesAnalyzePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};