// This file is auto-generated by @hey-api/openapi-ts

/**
 * Wrapper for STH Device class implementing Pydantic features
 */
export type STHDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
    rssi: number;
};

export type STUDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
};

export type SthApiV1DevicesSthGetResponse = Array<STHDeviceResponseModel>;

export type StuApiV1DevicesStuGetResponse = unknown | void;

export type PingApiV1PingGetResponse = unknown;

export type DelayApiV1DelayGetResponse = unknown;

export type OptionsApiV1OptionsResponse = unknown;

export type $OpenApiTs = {
    '/api/v1/devices/sth': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<STHDeviceResponseModel>;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/devices/stu': {
        get: {
            res: {
                /**
                 * Return the STU Devices connected to the system
                 */
                200: unknown;
                /**
                 * Indicates no STU Devices connected to the system
                 */
                204: void;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/ping': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/delay': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1*': {
        options: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};