// This file is auto-generated by @hey-api/openapi-ts

export type ADCValues = {
    prescaler: number | null;
    acquisition_time: number | null;
    oversampling_rate: number | null;
    reference_voltage: number | null;
};

export type Body_sth_connect_api_v1_sth_connect_put = {
    mac: string;
};

export type Body_stu_disable_ota_api_v1_stu_ota_disable_put = {
    name: string;
};

export type Body_stu_enable_ota_api_v1_stu_ota_enable_put = {
    name: string;
};

export type Body_stu_reset_api_v1_stu_reset_put = {
    name: string;
};

export type ConnectionTimeoutError = {
    name: string;
    message: string;
};

export type Error = {
    name: string;
    message: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NoResponseError = {
    name: string;
    message: string;
};

/**
 * Wrapper for STH Device class implementing Pydantic features
 */
export type STHDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
    rssi: number;
};

export type STHRenameRequestModel = {
    mac_address: string;
    new_name: string;
};

/**
 * Response Model for renaming a STH device
 */
export type STHRenameResponseModel = {
    name: string;
    old_name: string;
    mac_address: string;
};

export type STUDeviceResponseModel = {
    name: string;
    device_number: number;
    mac_address: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type StuApiV1StuGetResponse = unknown | void;

export type StuResetApiV1StuResetPutData = {
    requestBody: Body_stu_reset_api_v1_stu_reset_put;
};

export type StuResetApiV1StuResetPutResponse = void;

export type StuEnableOtaApiV1StuOtaEnablePutData = {
    requestBody: Body_stu_enable_ota_api_v1_stu_ota_enable_put;
};

export type StuEnableOtaApiV1StuOtaEnablePutResponse = NoResponseError | null;

export type StuDisableOtaApiV1StuOtaDisablePutData = {
    requestBody: Body_stu_disable_ota_api_v1_stu_ota_disable_put;
};

export type StuDisableOtaApiV1StuOtaDisablePutResponse = NoResponseError | null;

export type SthApiV1SthGetResponse = unknown;

export type SthConnectApiV1SthConnectPutData = {
    requestBody: Body_sth_connect_api_v1_sth_connect_put;
};

export type SthConnectApiV1SthConnectPutResponse = unknown;

export type SthDisconnectApiV1SthDisconnectPutResponse = unknown;

export type SthRenameApiV1SthRenamePutData = {
    requestBody: STHRenameRequestModel;
};

export type SthRenameApiV1SthRenamePutResponse = unknown;

export type ReadAdcApiV1SthReadAdcMacGetData = {
    mac: string;
};

export type ReadAdcApiV1SthReadAdcMacGetResponse = unknown;

export type PingApiV1PingGetResponse = unknown;

export type DelayApiV1DelayGetResponse = unknown;

export type OptionsApiV1OptionsResponse = unknown;

export type $OpenApiTs = {
    '/api/v1/stu': {
        get: {
            res: {
                /**
                 * Return the STU Devices connected to the system
                 */
                200: unknown;
                /**
                 * Indicates no STU Devices connected to the system
                 */
                204: void;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/stu/reset': {
        put: {
            req: StuResetApiV1StuResetPutData;
            res: {
                /**
                 * Device was successfully reset.
                 */
                204: void;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * The CAN Network did not respond. This can either be because the Node is not connected, or the Network is unresponsive.
                 */
                502: unknown;
            };
        };
    };
    '/api/v1/stu/ota/enable': {
        put: {
            req: StuEnableOtaApiV1StuOtaEnablePutData;
            res: {
                /**
                 * Successful Response
                 */
                200: NoResponseError | null;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/stu/ota/disable': {
        put: {
            req: StuDisableOtaApiV1StuOtaDisablePutData;
            res: {
                /**
                 * Successful Response
                 */
                200: NoResponseError | null;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/sth': {
        get: {
            res: {
                /**
                 * Return the STH Devices reachable
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/sth/connect': {
        put: {
            req: SthConnectApiV1SthConnectPutData;
            res: {
                /**
                 * Connection was successful
                 */
                200: unknown;
                /**
                 * Indicates no STH Devices in reach
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/sth/disconnect': {
        put: {
            res: {
                /**
                 * Disconnection was successful
                 */
                200: unknown;
                /**
                 * Indicates error in disconnection
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/sth/rename': {
        put: {
            req: SthRenameApiV1SthRenamePutData;
            res: {
                /**
                 * Rename was successful
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * Indicates error in rename
                 */
                502: unknown;
            };
        };
    };
    '/api/v1/sth/read-adc/{mac}': {
        get: {
            req: ReadAdcApiV1SthReadAdcMacGetData;
            res: {
                /**
                 * ADC reading was successful
                 */
                200: unknown;
                /**
                 * Not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * ADC reading timed out
                 */
                504: unknown;
            };
        };
    };
    '/api/v1/ping': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/delay': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1*': {
        options: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};